spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: root

